NET_INFO_PATH: ./data_config.yml
#Basic Path
DATASET_NAME: 128x128_FIX
#TRAINING_ORG_PATH : ["F:\\DIV2K_train_YUV"]

TRAINING_ORG_PATH: [D:/origCfP]
TEST_ORG_PATH: [D:/origCfP]
VALIDATION_ORG_PATH: []
DECODE_LOG_PATH: ./build_data/logs
TRAINING_BIN_PATH: [C:/Users/YangwooKim/Desktop/Codec/VVC4.0/samplebin_one]
#TRAINING_BIN_PATH : ["F:\\bin"]
#TRAINING_BIN_PATH : []

TEST_BIN_PATH: [C:/Users/YangwooKim/Desktop/Codec/VVC4.0/samplebin_one]
#TEST_BIN_PATH : []
VALIDATION_BIN_PATH: [C:/Users/YangwooKim/Desktop/Codec/VVC4.0/samplebin_one]
ADDITION_DATA: 1
IS_ONLY_ONE_INTRA: 0  #default zero, only use when you get png data



#Dataset Path
DECODER_PATH: ./build_data/DecoderApp.exe
DATASET_PATH: ./Dataset
TRAININGSET_PATH: Training
VALIDATIONSET_PATH: Validation
TESTSET_PATH: Test
SAMPLE_IMAGE_PATH: ImageSample
TEMP_PATH: ./temp
CSV_NAME: block_info.csv


#Dataset Number
TARGET_DATASET_NUM: 1000  # Training + Validation Set
VALIDATION_DATSET_NUM: 100
TARGET_TESTSET_NUM: 2  # [0 : All Frame, Others : A few frames ahead each Test Sequence]

#Dataset Shape Setting
USE_CONST_BLOCK: 1  # 0 : split by tu, 1 : split by const size
CONST_WIDTH: 128
CONST_HEIGHT: 128
SAVE_TU_CONST_BLOCK_INFO: 3  # 0 : Disable , 1 : Luma , 2 : Chroma, 3 : Dual
CONST_BLOCK_INTERVAL: 1

#TU Size
IS_TU_SPLIT: 0 # [1 : split by tu luma], [2 : split by tu Chroma]
MIN_WIDTH_SIZE: 1
MAX_WIDTH_SIZE: 128
MIN_HEIGHT_SIZE: 1
MAX_HEIGHT_SIZE: 128
ONLY_SQUARE: 0  # [0 : Rectangle and Square], [1 : Square]

#Dataset Format Setting
#Data Order : [OriginalY -> OriginalCbCr -> PredY -> PredCbCr -> FilteredReconY -> FilteredReconUV -> UnfilteredReconY -> UnfilteredReconUV]
ONLY_LUMA: 0  # [1 : YCbCr], [0: Y]
PEL_DATA: [1, 1, 1, 1]  # Origianal, Prediction, Reconstruction, UnfilteredRecon
#TU_MAP : [1, 1, 1] # Must Same Shape as TU_DATA_OTHERS


#Others Setting
SKIP_TU_DEPENDENT_QP: 0  # [0 : skip by binfile qp], [1: skip by tu dependent qp]
QP: [22, 27, 32, 37]
MODE: 1  # [0 : Intra&Inter], [1 : Only Intra], [2 : Only Inter]
INTRA_MODE: []  # if Empty, All mode
INTER_MODE: []
PARALLEL_DECODE: 1  # [1 : None parrallel processing], [Others : Thread number]
INTRA_TEMPORAL_SUBSAMPLE_RATIO: 8
DECODER_BIT_DEPTH: 10
TU_DATA_OTHERS: [QP, MODE, DEPTH]        # data order [width, height, x_pos, y_pos, others..]


#Padding Setting
LUMA_PAD: [2, 2, 2, 2] # [0 : None], [others : size] # [up, down, left, right]
CHROMA_PAD: [1, 1, 1, 1] # [0 : None], [others : size]
PIC_BOUNDARY_PAD: 1  # [-1 : minus one], [0 : Zeros], [1 : Same], [2 : without boundary block]


#Compensate Dataset Probabilty
OPT: 1  # [0: Random], [1: Compensate Block Area], [2: Compensate Block Error by MSE] [3: Compensate Block Error by Squared Error]
COMPARE_OPT: 3  # [1: Prediction], [2: Reconstruction], [3: Unfiltered] # Only 'OPT' option is 2 or 3
YUV_OPT: 0  # [0: YUV] , [1:Y], [2: UV] # Only 'OPT' option is 2 or 3

